package category.pojo;

import java.io.Serializable;

public class ResourceRecords implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_records.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_records.orderId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_records.resourceId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_records.resourceName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String resourcename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_records.resourceAmount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Double resourceamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_records.id
     *
     * @return the value of resource_records.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_records.id
     *
     * @param id the value for resource_records.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_records.orderId
     *
     * @return the value of resource_records.orderId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_records.orderId
     *
     * @param orderid the value for resource_records.orderId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_records.resourceId
     *
     * @return the value of resource_records.resourceId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_records.resourceId
     *
     * @param resourceid the value for resource_records.resourceId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setResourceid(String resourceid) {
        this.resourceid = resourceid == null ? null : resourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_records.resourceName
     *
     * @return the value of resource_records.resourceName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getResourcename() {
        return resourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_records.resourceName
     *
     * @param resourcename the value for resource_records.resourceName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setResourcename(String resourcename) {
        this.resourcename = resourcename == null ? null : resourcename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_records.resourceAmount
     *
     * @return the value of resource_records.resourceAmount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Double getResourceamount() {
        return resourceamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_records.resourceAmount
     *
     * @param resourceamount the value for resource_records.resourceAmount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setResourceamount(Double resourceamount) {
        this.resourceamount = resourceamount;
    }
}