package category.pojo;

import java.io.Serializable;

public class ResourceCategory implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_category.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_category.resourceId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_category.resourceName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String resourcename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_category.resourceType
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String resourcetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_category.resourcePrice
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Double resourceprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_category.resourceDescribe
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String resourcedescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_category.resourceStock
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Integer resourcestock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_category.resourcePicture
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String resourcepicture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_category.id
     *
     * @return the value of resource_category.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_category.id
     *
     * @param id the value for resource_category.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_category.resourceId
     *
     * @return the value of resource_category.resourceId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_category.resourceId
     *
     * @param resourceid the value for resource_category.resourceId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setResourceid(String resourceid) {
        this.resourceid = resourceid == null ? null : resourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_category.resourceName
     *
     * @return the value of resource_category.resourceName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getResourcename() {
        return resourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_category.resourceName
     *
     * @param resourcename the value for resource_category.resourceName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setResourcename(String resourcename) {
        this.resourcename = resourcename == null ? null : resourcename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_category.resourceType
     *
     * @return the value of resource_category.resourceType
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getResourcetype() {
        return resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_category.resourceType
     *
     * @param resourcetype the value for resource_category.resourceType
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setResourcetype(String resourcetype) {
        this.resourcetype = resourcetype == null ? null : resourcetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_category.resourcePrice
     *
     * @return the value of resource_category.resourcePrice
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Double getResourceprice() {
        return resourceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_category.resourcePrice
     *
     * @param resourceprice the value for resource_category.resourcePrice
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setResourceprice(Double resourceprice) {
        this.resourceprice = resourceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_category.resourceDescribe
     *
     * @return the value of resource_category.resourceDescribe
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getResourcedescribe() {
        return resourcedescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_category.resourceDescribe
     *
     * @param resourcedescribe the value for resource_category.resourceDescribe
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setResourcedescribe(String resourcedescribe) {
        this.resourcedescribe = resourcedescribe == null ? null : resourcedescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_category.resourceStock
     *
     * @return the value of resource_category.resourceStock
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Integer getResourcestock() {
        return resourcestock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_category.resourceStock
     *
     * @param resourcestock the value for resource_category.resourceStock
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setResourcestock(Integer resourcestock) {
        this.resourcestock = resourcestock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_category.resourcePicture
     *
     * @return the value of resource_category.resourcePicture
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getResourcepicture() {
        return resourcepicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_category.resourcePicture
     *
     * @param resourcepicture the value for resource_category.resourcePicture
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setResourcepicture(String resourcepicture) {
        this.resourcepicture = resourcepicture == null ? null : resourcepicture.trim();
    }
}