package order.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public OrderInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderId is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("orderId =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("orderId <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("orderId >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("orderId >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("orderId <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("orderId <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("orderId like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("orderId not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("orderId in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("orderId not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("orderId between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("orderId not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andSelleraccountIsNull() {
            addCriterion("sellerAccount is null");
            return (Criteria) this;
        }

        public Criteria andSelleraccountIsNotNull() {
            addCriterion("sellerAccount is not null");
            return (Criteria) this;
        }

        public Criteria andSelleraccountEqualTo(String value) {
            addCriterion("sellerAccount =", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountNotEqualTo(String value) {
            addCriterion("sellerAccount <>", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountGreaterThan(String value) {
            addCriterion("sellerAccount >", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountGreaterThanOrEqualTo(String value) {
            addCriterion("sellerAccount >=", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountLessThan(String value) {
            addCriterion("sellerAccount <", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountLessThanOrEqualTo(String value) {
            addCriterion("sellerAccount <=", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountLike(String value) {
            addCriterion("sellerAccount like", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountNotLike(String value) {
            addCriterion("sellerAccount not like", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountIn(List<String> values) {
            addCriterion("sellerAccount in", values, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountNotIn(List<String> values) {
            addCriterion("sellerAccount not in", values, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountBetween(String value1, String value2) {
            addCriterion("sellerAccount between", value1, value2, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountNotBetween(String value1, String value2) {
            addCriterion("sellerAccount not between", value1, value2, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountIsNull() {
            addCriterion("collectorAccount is null");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountIsNotNull() {
            addCriterion("collectorAccount is not null");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountEqualTo(String value) {
            addCriterion("collectorAccount =", value, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountNotEqualTo(String value) {
            addCriterion("collectorAccount <>", value, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountGreaterThan(String value) {
            addCriterion("collectorAccount >", value, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountGreaterThanOrEqualTo(String value) {
            addCriterion("collectorAccount >=", value, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountLessThan(String value) {
            addCriterion("collectorAccount <", value, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountLessThanOrEqualTo(String value) {
            addCriterion("collectorAccount <=", value, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountLike(String value) {
            addCriterion("collectorAccount like", value, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountNotLike(String value) {
            addCriterion("collectorAccount not like", value, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountIn(List<String> values) {
            addCriterion("collectorAccount in", values, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountNotIn(List<String> values) {
            addCriterion("collectorAccount not in", values, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountBetween(String value1, String value2) {
            addCriterion("collectorAccount between", value1, value2, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andCollectoraccountNotBetween(String value1, String value2) {
            addCriterion("collectorAccount not between", value1, value2, "collectoraccount");
            return (Criteria) this;
        }

        public Criteria andOrderamountIsNull() {
            addCriterion("orderAmount is null");
            return (Criteria) this;
        }

        public Criteria andOrderamountIsNotNull() {
            addCriterion("orderAmount is not null");
            return (Criteria) this;
        }

        public Criteria andOrderamountEqualTo(Double value) {
            addCriterion("orderAmount =", value, "orderamount");
            return (Criteria) this;
        }

        public Criteria andOrderamountNotEqualTo(Double value) {
            addCriterion("orderAmount <>", value, "orderamount");
            return (Criteria) this;
        }

        public Criteria andOrderamountGreaterThan(Double value) {
            addCriterion("orderAmount >", value, "orderamount");
            return (Criteria) this;
        }

        public Criteria andOrderamountGreaterThanOrEqualTo(Double value) {
            addCriterion("orderAmount >=", value, "orderamount");
            return (Criteria) this;
        }

        public Criteria andOrderamountLessThan(Double value) {
            addCriterion("orderAmount <", value, "orderamount");
            return (Criteria) this;
        }

        public Criteria andOrderamountLessThanOrEqualTo(Double value) {
            addCriterion("orderAmount <=", value, "orderamount");
            return (Criteria) this;
        }

        public Criteria andOrderamountIn(List<Double> values) {
            addCriterion("orderAmount in", values, "orderamount");
            return (Criteria) this;
        }

        public Criteria andOrderamountNotIn(List<Double> values) {
            addCriterion("orderAmount not in", values, "orderamount");
            return (Criteria) this;
        }

        public Criteria andOrderamountBetween(Double value1, Double value2) {
            addCriterion("orderAmount between", value1, value2, "orderamount");
            return (Criteria) this;
        }

        public Criteria andOrderamountNotBetween(Double value1, Double value2) {
            addCriterion("orderAmount not between", value1, value2, "orderamount");
            return (Criteria) this;
        }

        public Criteria andOrderstateIsNull() {
            addCriterion("orderState is null");
            return (Criteria) this;
        }

        public Criteria andOrderstateIsNotNull() {
            addCriterion("orderState is not null");
            return (Criteria) this;
        }

        public Criteria andOrderstateEqualTo(Integer value) {
            addCriterion("orderState =", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotEqualTo(Integer value) {
            addCriterion("orderState <>", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateGreaterThan(Integer value) {
            addCriterion("orderState >", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderState >=", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLessThan(Integer value) {
            addCriterion("orderState <", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLessThanOrEqualTo(Integer value) {
            addCriterion("orderState <=", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateIn(List<Integer> values) {
            addCriterion("orderState in", values, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotIn(List<Integer> values) {
            addCriterion("orderState not in", values, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateBetween(Integer value1, Integer value2) {
            addCriterion("orderState between", value1, value2, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotBetween(Integer value1, Integer value2) {
            addCriterion("orderState not between", value1, value2, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeIsNull() {
            addCriterion("orderPlaceTime is null");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeIsNotNull() {
            addCriterion("orderPlaceTime is not null");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeEqualTo(Date value) {
            addCriterion("orderPlaceTime =", value, "orderplacetime");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeNotEqualTo(Date value) {
            addCriterion("orderPlaceTime <>", value, "orderplacetime");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeGreaterThan(Date value) {
            addCriterion("orderPlaceTime >", value, "orderplacetime");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("orderPlaceTime >=", value, "orderplacetime");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeLessThan(Date value) {
            addCriterion("orderPlaceTime <", value, "orderplacetime");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeLessThanOrEqualTo(Date value) {
            addCriterion("orderPlaceTime <=", value, "orderplacetime");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeIn(List<Date> values) {
            addCriterion("orderPlaceTime in", values, "orderplacetime");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeNotIn(List<Date> values) {
            addCriterion("orderPlaceTime not in", values, "orderplacetime");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeBetween(Date value1, Date value2) {
            addCriterion("orderPlaceTime between", value1, value2, "orderplacetime");
            return (Criteria) this;
        }

        public Criteria andOrderplacetimeNotBetween(Date value1, Date value2) {
            addCriterion("orderPlaceTime not between", value1, value2, "orderplacetime");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeIsNull() {
            addCriterion("orderFinishTime is null");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeIsNotNull() {
            addCriterion("orderFinishTime is not null");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeEqualTo(Date value) {
            addCriterion("orderFinishTime =", value, "orderfinishtime");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeNotEqualTo(Date value) {
            addCriterion("orderFinishTime <>", value, "orderfinishtime");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeGreaterThan(Date value) {
            addCriterion("orderFinishTime >", value, "orderfinishtime");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("orderFinishTime >=", value, "orderfinishtime");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeLessThan(Date value) {
            addCriterion("orderFinishTime <", value, "orderfinishtime");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeLessThanOrEqualTo(Date value) {
            addCriterion("orderFinishTime <=", value, "orderfinishtime");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeIn(List<Date> values) {
            addCriterion("orderFinishTime in", values, "orderfinishtime");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeNotIn(List<Date> values) {
            addCriterion("orderFinishTime not in", values, "orderfinishtime");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeBetween(Date value1, Date value2) {
            addCriterion("orderFinishTime between", value1, value2, "orderfinishtime");
            return (Criteria) this;
        }

        public Criteria andOrderfinishtimeNotBetween(Date value1, Date value2) {
            addCriterion("orderFinishTime not between", value1, value2, "orderfinishtime");
            return (Criteria) this;
        }

        public Criteria andSellerlevelIsNull() {
            addCriterion("sellerLevel is null");
            return (Criteria) this;
        }

        public Criteria andSellerlevelIsNotNull() {
            addCriterion("sellerLevel is not null");
            return (Criteria) this;
        }

        public Criteria andSellerlevelEqualTo(String value) {
            addCriterion("sellerLevel =", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelNotEqualTo(String value) {
            addCriterion("sellerLevel <>", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelGreaterThan(String value) {
            addCriterion("sellerLevel >", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelGreaterThanOrEqualTo(String value) {
            addCriterion("sellerLevel >=", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelLessThan(String value) {
            addCriterion("sellerLevel <", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelLessThanOrEqualTo(String value) {
            addCriterion("sellerLevel <=", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelLike(String value) {
            addCriterion("sellerLevel like", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelNotLike(String value) {
            addCriterion("sellerLevel not like", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelIn(List<String> values) {
            addCriterion("sellerLevel in", values, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelNotIn(List<String> values) {
            addCriterion("sellerLevel not in", values, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelBetween(String value1, String value2) {
            addCriterion("sellerLevel between", value1, value2, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelNotBetween(String value1, String value2) {
            addCriterion("sellerLevel not between", value1, value2, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellermessageIsNull() {
            addCriterion("sellerMessage is null");
            return (Criteria) this;
        }

        public Criteria andSellermessageIsNotNull() {
            addCriterion("sellerMessage is not null");
            return (Criteria) this;
        }

        public Criteria andSellermessageEqualTo(String value) {
            addCriterion("sellerMessage =", value, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageNotEqualTo(String value) {
            addCriterion("sellerMessage <>", value, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageGreaterThan(String value) {
            addCriterion("sellerMessage >", value, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageGreaterThanOrEqualTo(String value) {
            addCriterion("sellerMessage >=", value, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageLessThan(String value) {
            addCriterion("sellerMessage <", value, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageLessThanOrEqualTo(String value) {
            addCriterion("sellerMessage <=", value, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageLike(String value) {
            addCriterion("sellerMessage like", value, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageNotLike(String value) {
            addCriterion("sellerMessage not like", value, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageIn(List<String> values) {
            addCriterion("sellerMessage in", values, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageNotIn(List<String> values) {
            addCriterion("sellerMessage not in", values, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageBetween(String value1, String value2) {
            addCriterion("sellerMessage between", value1, value2, "sellermessage");
            return (Criteria) this;
        }

        public Criteria andSellermessageNotBetween(String value1, String value2) {
            addCriterion("sellerMessage not between", value1, value2, "sellermessage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderinfo
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 15 10:40:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderinfo
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}