package order.pojo;

import java.io.Serializable;
import java.util.Date;

public class OrderInfo  implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.sellerAccount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String selleraccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.collectorAccount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String collectoraccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderAmount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Double orderamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderState
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Integer orderstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderPlaceTime
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Date orderplacetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderFinishTime
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Date orderfinishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.sellerLevel
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String sellerlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.sellerMessage
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String sellermessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.id
     *
     * @return the value of orderinfo.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.id
     *
     * @param id the value for orderinfo.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderId
     *
     * @return the value of orderinfo.orderId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderId
     *
     * @param orderid the value for orderinfo.orderId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.sellerAccount
     *
     * @return the value of orderinfo.sellerAccount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getSelleraccount() {
        return selleraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.sellerAccount
     *
     * @param selleraccount the value for orderinfo.sellerAccount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setSelleraccount(String selleraccount) {
        this.selleraccount = selleraccount == null ? null : selleraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.collectorAccount
     *
     * @return the value of orderinfo.collectorAccount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getCollectoraccount() {
        return collectoraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.collectorAccount
     *
     * @param collectoraccount the value for orderinfo.collectorAccount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setCollectoraccount(String collectoraccount) {
        this.collectoraccount = collectoraccount == null ? null : collectoraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderAmount
     *
     * @return the value of orderinfo.orderAmount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Double getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderAmount
     *
     * @param orderamount the value for orderinfo.orderAmount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setOrderamount(Double orderamount) {
        this.orderamount = orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderState
     *
     * @return the value of orderinfo.orderState
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Integer getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderState
     *
     * @param orderstate the value for orderinfo.orderState
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setOrderstate(Integer orderstate) {
        this.orderstate = orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderPlaceTime
     *
     * @return the value of orderinfo.orderPlaceTime
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Date getOrderplacetime() {
        return orderplacetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderPlaceTime
     *
     * @param orderplacetime the value for orderinfo.orderPlaceTime
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setOrderplacetime(Date orderplacetime) {
        this.orderplacetime = orderplacetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderFinishTime
     *
     * @return the value of orderinfo.orderFinishTime
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Date getOrderfinishtime() {
        return orderfinishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderFinishTime
     *
     * @param orderfinishtime the value for orderinfo.orderFinishTime
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setOrderfinishtime(Date orderfinishtime) {
        this.orderfinishtime = orderfinishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.sellerLevel
     *
     * @return the value of orderinfo.sellerLevel
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getSellerlevel() {
        return sellerlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.sellerLevel
     *
     * @param sellerlevel the value for orderinfo.sellerLevel
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setSellerlevel(String sellerlevel) {
        this.sellerlevel = sellerlevel == null ? null : sellerlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.sellerMessage
     *
     * @return the value of orderinfo.sellerMessage
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getSellermessage() {
        return sellermessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.sellerMessage
     *
     * @param sellermessage the value for orderinfo.sellerMessage
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setSellermessage(String sellermessage) {
        this.sellermessage = sellermessage == null ? null : sellermessage.trim();
    }
}