package user.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import user.pojo.Collector;
import user.pojo.CollectorExample;

@Mapper
public interface CollectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    long countByExample(CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int deleteByExample(CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int insert(Collector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int insertSelective(Collector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    List<Collector> selectByExample(CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    Collector selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") Collector record, @Param("example") CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int updateByExample(@Param("record") Collector record, @Param("example") CollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int updateByPrimaryKeySelective(Collector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collector
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int updateByPrimaryKey(Collector record);
}