package category.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import category.pojo.ResourceCategory;
import category.pojo.ResourceCategoryExample;

public interface ResourceCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    long countByExample(ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int deleteByExample(ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int insert(ResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int insertSelective(ResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    List<ResourceCategory> selectByExample(ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    ResourceCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") ResourceCategory record, @Param("example") ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int updateByExample(@Param("record") ResourceCategory record, @Param("example") ResourceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int updateByPrimaryKeySelective(ResourceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_category
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    int updateByPrimaryKey(ResourceCategory record);
}