package user.pojo;

import java.util.ArrayList;
import java.util.List;

public class AddressExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public AddressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAddressidIsNull() {
            addCriterion("addressId is null");
            return (Criteria) this;
        }

        public Criteria andAddressidIsNotNull() {
            addCriterion("addressId is not null");
            return (Criteria) this;
        }

        public Criteria andAddressidEqualTo(String value) {
            addCriterion("addressId =", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotEqualTo(String value) {
            addCriterion("addressId <>", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThan(String value) {
            addCriterion("addressId >", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidGreaterThanOrEqualTo(String value) {
            addCriterion("addressId >=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThan(String value) {
            addCriterion("addressId <", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLessThanOrEqualTo(String value) {
            addCriterion("addressId <=", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidLike(String value) {
            addCriterion("addressId like", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotLike(String value) {
            addCriterion("addressId not like", value, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidIn(List<String> values) {
            addCriterion("addressId in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotIn(List<String> values) {
            addCriterion("addressId not in", values, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidBetween(String value1, String value2) {
            addCriterion("addressId between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressidNotBetween(String value1, String value2) {
            addCriterion("addressId not between", value1, value2, "addressid");
            return (Criteria) this;
        }

        public Criteria andAddressareaIsNull() {
            addCriterion("addressArea is null");
            return (Criteria) this;
        }

        public Criteria andAddressareaIsNotNull() {
            addCriterion("addressArea is not null");
            return (Criteria) this;
        }

        public Criteria andAddressareaEqualTo(String value) {
            addCriterion("addressArea =", value, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaNotEqualTo(String value) {
            addCriterion("addressArea <>", value, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaGreaterThan(String value) {
            addCriterion("addressArea >", value, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaGreaterThanOrEqualTo(String value) {
            addCriterion("addressArea >=", value, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaLessThan(String value) {
            addCriterion("addressArea <", value, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaLessThanOrEqualTo(String value) {
            addCriterion("addressArea <=", value, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaLike(String value) {
            addCriterion("addressArea like", value, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaNotLike(String value) {
            addCriterion("addressArea not like", value, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaIn(List<String> values) {
            addCriterion("addressArea in", values, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaNotIn(List<String> values) {
            addCriterion("addressArea not in", values, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaBetween(String value1, String value2) {
            addCriterion("addressArea between", value1, value2, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressareaNotBetween(String value1, String value2) {
            addCriterion("addressArea not between", value1, value2, "addressarea");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedIsNull() {
            addCriterion("addressDetailed is null");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedIsNotNull() {
            addCriterion("addressDetailed is not null");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedEqualTo(String value) {
            addCriterion("addressDetailed =", value, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedNotEqualTo(String value) {
            addCriterion("addressDetailed <>", value, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedGreaterThan(String value) {
            addCriterion("addressDetailed >", value, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedGreaterThanOrEqualTo(String value) {
            addCriterion("addressDetailed >=", value, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedLessThan(String value) {
            addCriterion("addressDetailed <", value, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedLessThanOrEqualTo(String value) {
            addCriterion("addressDetailed <=", value, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedLike(String value) {
            addCriterion("addressDetailed like", value, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedNotLike(String value) {
            addCriterion("addressDetailed not like", value, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedIn(List<String> values) {
            addCriterion("addressDetailed in", values, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedNotIn(List<String> values) {
            addCriterion("addressDetailed not in", values, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedBetween(String value1, String value2) {
            addCriterion("addressDetailed between", value1, value2, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressdetailedNotBetween(String value1, String value2) {
            addCriterion("addressDetailed not between", value1, value2, "addressdetailed");
            return (Criteria) this;
        }

        public Criteria andAddressnameIsNull() {
            addCriterion("addressName is null");
            return (Criteria) this;
        }

        public Criteria andAddressnameIsNotNull() {
            addCriterion("addressName is not null");
            return (Criteria) this;
        }

        public Criteria andAddressnameEqualTo(String value) {
            addCriterion("addressName =", value, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameNotEqualTo(String value) {
            addCriterion("addressName <>", value, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameGreaterThan(String value) {
            addCriterion("addressName >", value, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameGreaterThanOrEqualTo(String value) {
            addCriterion("addressName >=", value, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameLessThan(String value) {
            addCriterion("addressName <", value, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameLessThanOrEqualTo(String value) {
            addCriterion("addressName <=", value, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameLike(String value) {
            addCriterion("addressName like", value, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameNotLike(String value) {
            addCriterion("addressName not like", value, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameIn(List<String> values) {
            addCriterion("addressName in", values, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameNotIn(List<String> values) {
            addCriterion("addressName not in", values, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameBetween(String value1, String value2) {
            addCriterion("addressName between", value1, value2, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressnameNotBetween(String value1, String value2) {
            addCriterion("addressName not between", value1, value2, "addressname");
            return (Criteria) this;
        }

        public Criteria andAddressphoneIsNull() {
            addCriterion("addressPhone is null");
            return (Criteria) this;
        }

        public Criteria andAddressphoneIsNotNull() {
            addCriterion("addressPhone is not null");
            return (Criteria) this;
        }

        public Criteria andAddressphoneEqualTo(String value) {
            addCriterion("addressPhone =", value, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneNotEqualTo(String value) {
            addCriterion("addressPhone <>", value, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneGreaterThan(String value) {
            addCriterion("addressPhone >", value, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneGreaterThanOrEqualTo(String value) {
            addCriterion("addressPhone >=", value, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneLessThan(String value) {
            addCriterion("addressPhone <", value, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneLessThanOrEqualTo(String value) {
            addCriterion("addressPhone <=", value, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneLike(String value) {
            addCriterion("addressPhone like", value, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneNotLike(String value) {
            addCriterion("addressPhone not like", value, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneIn(List<String> values) {
            addCriterion("addressPhone in", values, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneNotIn(List<String> values) {
            addCriterion("addressPhone not in", values, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneBetween(String value1, String value2) {
            addCriterion("addressPhone between", value1, value2, "addressphone");
            return (Criteria) this;
        }

        public Criteria andAddressphoneNotBetween(String value1, String value2) {
            addCriterion("addressPhone not between", value1, value2, "addressphone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 15 10:40:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table address
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}