package user.pojo;

import java.io.Serializable;

public class Admin implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String adminname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPassword
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String adminpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPhone
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String adminphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPicture
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String adminpicture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminId
     *
     * @return the value of admin.adminId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminId
     *
     * @param adminid the value for admin.adminId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminName
     *
     * @return the value of admin.adminName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminName
     *
     * @param adminname the value for admin.adminName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPassword
     *
     * @return the value of admin.adminPassword
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getAdminpassword() {
        return adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPassword
     *
     * @param adminpassword the value for admin.adminPassword
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setAdminpassword(String adminpassword) {
        this.adminpassword = adminpassword == null ? null : adminpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPhone
     *
     * @return the value of admin.adminPhone
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getAdminphone() {
        return adminphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPhone
     *
     * @param adminphone the value for admin.adminPhone
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setAdminphone(String adminphone) {
        this.adminphone = adminphone == null ? null : adminphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPicture
     *
     * @return the value of admin.adminPicture
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getAdminpicture() {
        return adminpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPicture
     *
     * @param adminpicture the value for admin.adminPicture
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setAdminpicture(String adminpicture) {
        this.adminpicture = adminpicture == null ? null : adminpicture.trim();
    }
}