package user.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdminlogExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public AdminlogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNull() {
            addCriterion("adminId is null");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNotNull() {
            addCriterion("adminId is not null");
            return (Criteria) this;
        }

        public Criteria andAdminidEqualTo(String value) {
            addCriterion("adminId =", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotEqualTo(String value) {
            addCriterion("adminId <>", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThan(String value) {
            addCriterion("adminId >", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThanOrEqualTo(String value) {
            addCriterion("adminId >=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThan(String value) {
            addCriterion("adminId <", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThanOrEqualTo(String value) {
            addCriterion("adminId <=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLike(String value) {
            addCriterion("adminId like", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotLike(String value) {
            addCriterion("adminId not like", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidIn(List<String> values) {
            addCriterion("adminId in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotIn(List<String> values) {
            addCriterion("adminId not in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidBetween(String value1, String value2) {
            addCriterion("adminId between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotBetween(String value1, String value2) {
            addCriterion("adminId not between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeIsNull() {
            addCriterion("adminOperationTime is null");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeIsNotNull() {
            addCriterion("adminOperationTime is not null");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeEqualTo(Date value) {
            addCriterion("adminOperationTime =", value, "adminoperationtime");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeNotEqualTo(Date value) {
            addCriterion("adminOperationTime <>", value, "adminoperationtime");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeGreaterThan(Date value) {
            addCriterion("adminOperationTime >", value, "adminoperationtime");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("adminOperationTime >=", value, "adminoperationtime");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeLessThan(Date value) {
            addCriterion("adminOperationTime <", value, "adminoperationtime");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeLessThanOrEqualTo(Date value) {
            addCriterion("adminOperationTime <=", value, "adminoperationtime");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeIn(List<Date> values) {
            addCriterion("adminOperationTime in", values, "adminoperationtime");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeNotIn(List<Date> values) {
            addCriterion("adminOperationTime not in", values, "adminoperationtime");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeBetween(Date value1, Date value2) {
            addCriterion("adminOperationTime between", value1, value2, "adminoperationtime");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtimeNotBetween(Date value1, Date value2) {
            addCriterion("adminOperationTime not between", value1, value2, "adminoperationtime");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableIsNull() {
            addCriterion("adminOperationTable is null");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableIsNotNull() {
            addCriterion("adminOperationTable is not null");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableEqualTo(String value) {
            addCriterion("adminOperationTable =", value, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableNotEqualTo(String value) {
            addCriterion("adminOperationTable <>", value, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableGreaterThan(String value) {
            addCriterion("adminOperationTable >", value, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableGreaterThanOrEqualTo(String value) {
            addCriterion("adminOperationTable >=", value, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableLessThan(String value) {
            addCriterion("adminOperationTable <", value, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableLessThanOrEqualTo(String value) {
            addCriterion("adminOperationTable <=", value, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableLike(String value) {
            addCriterion("adminOperationTable like", value, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableNotLike(String value) {
            addCriterion("adminOperationTable not like", value, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableIn(List<String> values) {
            addCriterion("adminOperationTable in", values, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableNotIn(List<String> values) {
            addCriterion("adminOperationTable not in", values, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableBetween(String value1, String value2) {
            addCriterion("adminOperationTable between", value1, value2, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationtableNotBetween(String value1, String value2) {
            addCriterion("adminOperationTable not between", value1, value2, "adminoperationtable");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionIsNull() {
            addCriterion("adminOperationAction is null");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionIsNotNull() {
            addCriterion("adminOperationAction is not null");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionEqualTo(String value) {
            addCriterion("adminOperationAction =", value, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionNotEqualTo(String value) {
            addCriterion("adminOperationAction <>", value, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionGreaterThan(String value) {
            addCriterion("adminOperationAction >", value, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionGreaterThanOrEqualTo(String value) {
            addCriterion("adminOperationAction >=", value, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionLessThan(String value) {
            addCriterion("adminOperationAction <", value, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionLessThanOrEqualTo(String value) {
            addCriterion("adminOperationAction <=", value, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionLike(String value) {
            addCriterion("adminOperationAction like", value, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionNotLike(String value) {
            addCriterion("adminOperationAction not like", value, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionIn(List<String> values) {
            addCriterion("adminOperationAction in", values, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionNotIn(List<String> values) {
            addCriterion("adminOperationAction not in", values, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionBetween(String value1, String value2) {
            addCriterion("adminOperationAction between", value1, value2, "adminoperationaction");
            return (Criteria) this;
        }

        public Criteria andAdminoperationactionNotBetween(String value1, String value2) {
            addCriterion("adminOperationAction not between", value1, value2, "adminoperationaction");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminlog
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 15 10:40:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adminlog
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}