package user.pojo;

import java.io.Serializable;
import java.util.Date;

public class Collector implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.collectorAccount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String collectoraccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.collectorName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String collectorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.collectorPhone
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String collectorphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.collectorOpenid
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String collectoropenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.addressId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.collectorRegisterDate
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Date collectorregisterdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.collectorBalance
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private Double collectorbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.collectorLevel
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String collectorlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.collectorPicture
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String collectorpicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collector.collectorPassword
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    private String collectorpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.id
     *
     * @return the value of collector.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.id
     *
     * @param id the value for collector.id
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.collectorAccount
     *
     * @return the value of collector.collectorAccount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getCollectoraccount() {
        return collectoraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.collectorAccount
     *
     * @param collectoraccount the value for collector.collectorAccount
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setCollectoraccount(String collectoraccount) {
        this.collectoraccount = collectoraccount == null ? null : collectoraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.collectorName
     *
     * @return the value of collector.collectorName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getCollectorname() {
        return collectorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.collectorName
     *
     * @param collectorname the value for collector.collectorName
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setCollectorname(String collectorname) {
        this.collectorname = collectorname == null ? null : collectorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.collectorPhone
     *
     * @return the value of collector.collectorPhone
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getCollectorphone() {
        return collectorphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.collectorPhone
     *
     * @param collectorphone the value for collector.collectorPhone
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setCollectorphone(String collectorphone) {
        this.collectorphone = collectorphone == null ? null : collectorphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.collectorOpenid
     *
     * @return the value of collector.collectorOpenid
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getCollectoropenid() {
        return collectoropenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.collectorOpenid
     *
     * @param collectoropenid the value for collector.collectorOpenid
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setCollectoropenid(String collectoropenid) {
        this.collectoropenid = collectoropenid == null ? null : collectoropenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.addressId
     *
     * @return the value of collector.addressId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.addressId
     *
     * @param addressid the value for collector.addressId
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setAddressid(String addressid) {
        this.addressid = addressid == null ? null : addressid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.collectorRegisterDate
     *
     * @return the value of collector.collectorRegisterDate
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Date getCollectorregisterdate() {
        return collectorregisterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.collectorRegisterDate
     *
     * @param collectorregisterdate the value for collector.collectorRegisterDate
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setCollectorregisterdate(Date collectorregisterdate) {
        this.collectorregisterdate = collectorregisterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.collectorBalance
     *
     * @return the value of collector.collectorBalance
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Double getCollectorbalance() {
        return collectorbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.collectorBalance
     *
     * @param collectorbalance the value for collector.collectorBalance
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setCollectorbalance(Double collectorbalance) {
        this.collectorbalance = collectorbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.collectorLevel
     *
     * @return the value of collector.collectorLevel
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getCollectorlevel() {
        return collectorlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.collectorLevel
     *
     * @param collectorlevel the value for collector.collectorLevel
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setCollectorlevel(String collectorlevel) {
        this.collectorlevel = collectorlevel == null ? null : collectorlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.collectorPicture
     *
     * @return the value of collector.collectorPicture
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getCollectorpicture() {
        return collectorpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.collectorPicture
     *
     * @param collectorpicture the value for collector.collectorPicture
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setCollectorpicture(String collectorpicture) {
        this.collectorpicture = collectorpicture == null ? null : collectorpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collector.collectorPassword
     *
     * @return the value of collector.collectorPassword
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getCollectorpassword() {
        return collectorpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collector.collectorPassword
     *
     * @param collectorpassword the value for collector.collectorPassword
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setCollectorpassword(String collectorpassword) {
        this.collectorpassword = collectorpassword == null ? null : collectorpassword.trim();
    }
}