package user.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SellerExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public SellerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSelleraccountIsNull() {
            addCriterion("sellerAccount is null");
            return (Criteria) this;
        }

        public Criteria andSelleraccountIsNotNull() {
            addCriterion("sellerAccount is not null");
            return (Criteria) this;
        }

        public Criteria andSelleraccountEqualTo(String value) {
            addCriterion("sellerAccount =", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountNotEqualTo(String value) {
            addCriterion("sellerAccount <>", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountGreaterThan(String value) {
            addCriterion("sellerAccount >", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountGreaterThanOrEqualTo(String value) {
            addCriterion("sellerAccount >=", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountLessThan(String value) {
            addCriterion("sellerAccount <", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountLessThanOrEqualTo(String value) {
            addCriterion("sellerAccount <=", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountLike(String value) {
            addCriterion("sellerAccount like", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountNotLike(String value) {
            addCriterion("sellerAccount not like", value, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountIn(List<String> values) {
            addCriterion("sellerAccount in", values, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountNotIn(List<String> values) {
            addCriterion("sellerAccount not in", values, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountBetween(String value1, String value2) {
            addCriterion("sellerAccount between", value1, value2, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSelleraccountNotBetween(String value1, String value2) {
            addCriterion("sellerAccount not between", value1, value2, "selleraccount");
            return (Criteria) this;
        }

        public Criteria andSellernameIsNull() {
            addCriterion("sellerName is null");
            return (Criteria) this;
        }

        public Criteria andSellernameIsNotNull() {
            addCriterion("sellerName is not null");
            return (Criteria) this;
        }

        public Criteria andSellernameEqualTo(String value) {
            addCriterion("sellerName =", value, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameNotEqualTo(String value) {
            addCriterion("sellerName <>", value, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameGreaterThan(String value) {
            addCriterion("sellerName >", value, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameGreaterThanOrEqualTo(String value) {
            addCriterion("sellerName >=", value, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameLessThan(String value) {
            addCriterion("sellerName <", value, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameLessThanOrEqualTo(String value) {
            addCriterion("sellerName <=", value, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameLike(String value) {
            addCriterion("sellerName like", value, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameNotLike(String value) {
            addCriterion("sellerName not like", value, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameIn(List<String> values) {
            addCriterion("sellerName in", values, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameNotIn(List<String> values) {
            addCriterion("sellerName not in", values, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameBetween(String value1, String value2) {
            addCriterion("sellerName between", value1, value2, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellernameNotBetween(String value1, String value2) {
            addCriterion("sellerName not between", value1, value2, "sellername");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordIsNull() {
            addCriterion("sellerPassword is null");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordIsNotNull() {
            addCriterion("sellerPassword is not null");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordEqualTo(String value) {
            addCriterion("sellerPassword =", value, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordNotEqualTo(String value) {
            addCriterion("sellerPassword <>", value, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordGreaterThan(String value) {
            addCriterion("sellerPassword >", value, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("sellerPassword >=", value, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordLessThan(String value) {
            addCriterion("sellerPassword <", value, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordLessThanOrEqualTo(String value) {
            addCriterion("sellerPassword <=", value, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordLike(String value) {
            addCriterion("sellerPassword like", value, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordNotLike(String value) {
            addCriterion("sellerPassword not like", value, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordIn(List<String> values) {
            addCriterion("sellerPassword in", values, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordNotIn(List<String> values) {
            addCriterion("sellerPassword not in", values, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordBetween(String value1, String value2) {
            addCriterion("sellerPassword between", value1, value2, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSellerpasswordNotBetween(String value1, String value2) {
            addCriterion("sellerPassword not between", value1, value2, "sellerpassword");
            return (Criteria) this;
        }

        public Criteria andSelleropenidIsNull() {
            addCriterion("sellerOpenid is null");
            return (Criteria) this;
        }

        public Criteria andSelleropenidIsNotNull() {
            addCriterion("sellerOpenid is not null");
            return (Criteria) this;
        }

        public Criteria andSelleropenidEqualTo(String value) {
            addCriterion("sellerOpenid =", value, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidNotEqualTo(String value) {
            addCriterion("sellerOpenid <>", value, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidGreaterThan(String value) {
            addCriterion("sellerOpenid >", value, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidGreaterThanOrEqualTo(String value) {
            addCriterion("sellerOpenid >=", value, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidLessThan(String value) {
            addCriterion("sellerOpenid <", value, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidLessThanOrEqualTo(String value) {
            addCriterion("sellerOpenid <=", value, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidLike(String value) {
            addCriterion("sellerOpenid like", value, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidNotLike(String value) {
            addCriterion("sellerOpenid not like", value, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidIn(List<String> values) {
            addCriterion("sellerOpenid in", values, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidNotIn(List<String> values) {
            addCriterion("sellerOpenid not in", values, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidBetween(String value1, String value2) {
            addCriterion("sellerOpenid between", value1, value2, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSelleropenidNotBetween(String value1, String value2) {
            addCriterion("sellerOpenid not between", value1, value2, "selleropenid");
            return (Criteria) this;
        }

        public Criteria andSellerphoneIsNull() {
            addCriterion("sellerPhone is null");
            return (Criteria) this;
        }

        public Criteria andSellerphoneIsNotNull() {
            addCriterion("sellerPhone is not null");
            return (Criteria) this;
        }

        public Criteria andSellerphoneEqualTo(String value) {
            addCriterion("sellerPhone =", value, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneNotEqualTo(String value) {
            addCriterion("sellerPhone <>", value, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneGreaterThan(String value) {
            addCriterion("sellerPhone >", value, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneGreaterThanOrEqualTo(String value) {
            addCriterion("sellerPhone >=", value, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneLessThan(String value) {
            addCriterion("sellerPhone <", value, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneLessThanOrEqualTo(String value) {
            addCriterion("sellerPhone <=", value, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneLike(String value) {
            addCriterion("sellerPhone like", value, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneNotLike(String value) {
            addCriterion("sellerPhone not like", value, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneIn(List<String> values) {
            addCriterion("sellerPhone in", values, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneNotIn(List<String> values) {
            addCriterion("sellerPhone not in", values, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneBetween(String value1, String value2) {
            addCriterion("sellerPhone between", value1, value2, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerphoneNotBetween(String value1, String value2) {
            addCriterion("sellerPhone not between", value1, value2, "sellerphone");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceIsNull() {
            addCriterion("sellerBalance is null");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceIsNotNull() {
            addCriterion("sellerBalance is not null");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceEqualTo(Double value) {
            addCriterion("sellerBalance =", value, "sellerbalance");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceNotEqualTo(Double value) {
            addCriterion("sellerBalance <>", value, "sellerbalance");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceGreaterThan(Double value) {
            addCriterion("sellerBalance >", value, "sellerbalance");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceGreaterThanOrEqualTo(Double value) {
            addCriterion("sellerBalance >=", value, "sellerbalance");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceLessThan(Double value) {
            addCriterion("sellerBalance <", value, "sellerbalance");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceLessThanOrEqualTo(Double value) {
            addCriterion("sellerBalance <=", value, "sellerbalance");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceIn(List<Double> values) {
            addCriterion("sellerBalance in", values, "sellerbalance");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceNotIn(List<Double> values) {
            addCriterion("sellerBalance not in", values, "sellerbalance");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceBetween(Double value1, Double value2) {
            addCriterion("sellerBalance between", value1, value2, "sellerbalance");
            return (Criteria) this;
        }

        public Criteria andSellerbalanceNotBetween(Double value1, Double value2) {
            addCriterion("sellerBalance not between", value1, value2, "sellerbalance");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateIsNull() {
            addCriterion("sellerRigisterDate is null");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateIsNotNull() {
            addCriterion("sellerRigisterDate is not null");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateEqualTo(Date value) {
            addCriterion("sellerRigisterDate =", value, "sellerrigisterdate");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateNotEqualTo(Date value) {
            addCriterion("sellerRigisterDate <>", value, "sellerrigisterdate");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateGreaterThan(Date value) {
            addCriterion("sellerRigisterDate >", value, "sellerrigisterdate");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateGreaterThanOrEqualTo(Date value) {
            addCriterion("sellerRigisterDate >=", value, "sellerrigisterdate");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateLessThan(Date value) {
            addCriterion("sellerRigisterDate <", value, "sellerrigisterdate");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateLessThanOrEqualTo(Date value) {
            addCriterion("sellerRigisterDate <=", value, "sellerrigisterdate");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateIn(List<Date> values) {
            addCriterion("sellerRigisterDate in", values, "sellerrigisterdate");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateNotIn(List<Date> values) {
            addCriterion("sellerRigisterDate not in", values, "sellerrigisterdate");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateBetween(Date value1, Date value2) {
            addCriterion("sellerRigisterDate between", value1, value2, "sellerrigisterdate");
            return (Criteria) this;
        }

        public Criteria andSellerrigisterdateNotBetween(Date value1, Date value2) {
            addCriterion("sellerRigisterDate not between", value1, value2, "sellerrigisterdate");
            return (Criteria) this;
        }

        public Criteria andSellerlevelIsNull() {
            addCriterion("sellerLevel is null");
            return (Criteria) this;
        }

        public Criteria andSellerlevelIsNotNull() {
            addCriterion("sellerLevel is not null");
            return (Criteria) this;
        }

        public Criteria andSellerlevelEqualTo(String value) {
            addCriterion("sellerLevel =", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelNotEqualTo(String value) {
            addCriterion("sellerLevel <>", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelGreaterThan(String value) {
            addCriterion("sellerLevel >", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelGreaterThanOrEqualTo(String value) {
            addCriterion("sellerLevel >=", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelLessThan(String value) {
            addCriterion("sellerLevel <", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelLessThanOrEqualTo(String value) {
            addCriterion("sellerLevel <=", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelLike(String value) {
            addCriterion("sellerLevel like", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelNotLike(String value) {
            addCriterion("sellerLevel not like", value, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelIn(List<String> values) {
            addCriterion("sellerLevel in", values, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelNotIn(List<String> values) {
            addCriterion("sellerLevel not in", values, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelBetween(String value1, String value2) {
            addCriterion("sellerLevel between", value1, value2, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerlevelNotBetween(String value1, String value2) {
            addCriterion("sellerLevel not between", value1, value2, "sellerlevel");
            return (Criteria) this;
        }

        public Criteria andSellerpictureIsNull() {
            addCriterion("sellerPicture is null");
            return (Criteria) this;
        }

        public Criteria andSellerpictureIsNotNull() {
            addCriterion("sellerPicture is not null");
            return (Criteria) this;
        }

        public Criteria andSellerpictureEqualTo(String value) {
            addCriterion("sellerPicture =", value, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureNotEqualTo(String value) {
            addCriterion("sellerPicture <>", value, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureGreaterThan(String value) {
            addCriterion("sellerPicture >", value, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureGreaterThanOrEqualTo(String value) {
            addCriterion("sellerPicture >=", value, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureLessThan(String value) {
            addCriterion("sellerPicture <", value, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureLessThanOrEqualTo(String value) {
            addCriterion("sellerPicture <=", value, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureLike(String value) {
            addCriterion("sellerPicture like", value, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureNotLike(String value) {
            addCriterion("sellerPicture not like", value, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureIn(List<String> values) {
            addCriterion("sellerPicture in", values, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureNotIn(List<String> values) {
            addCriterion("sellerPicture not in", values, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureBetween(String value1, String value2) {
            addCriterion("sellerPicture between", value1, value2, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andSellerpictureNotBetween(String value1, String value2) {
            addCriterion("sellerPicture not between", value1, value2, "sellerpicture");
            return (Criteria) this;
        }

        public Criteria andXsiteIsNull() {
            addCriterion("xSite is null");
            return (Criteria) this;
        }

        public Criteria andXsiteIsNotNull() {
            addCriterion("xSite is not null");
            return (Criteria) this;
        }

        public Criteria andXsiteEqualTo(Double value) {
            addCriterion("xSite =", value, "xsite");
            return (Criteria) this;
        }

        public Criteria andXsiteNotEqualTo(Double value) {
            addCriterion("xSite <>", value, "xsite");
            return (Criteria) this;
        }

        public Criteria andXsiteGreaterThan(Double value) {
            addCriterion("xSite >", value, "xsite");
            return (Criteria) this;
        }

        public Criteria andXsiteGreaterThanOrEqualTo(Double value) {
            addCriterion("xSite >=", value, "xsite");
            return (Criteria) this;
        }

        public Criteria andXsiteLessThan(Double value) {
            addCriterion("xSite <", value, "xsite");
            return (Criteria) this;
        }

        public Criteria andXsiteLessThanOrEqualTo(Double value) {
            addCriterion("xSite <=", value, "xsite");
            return (Criteria) this;
        }

        public Criteria andXsiteIn(List<Double> values) {
            addCriterion("xSite in", values, "xsite");
            return (Criteria) this;
        }

        public Criteria andXsiteNotIn(List<Double> values) {
            addCriterion("xSite not in", values, "xsite");
            return (Criteria) this;
        }

        public Criteria andXsiteBetween(Double value1, Double value2) {
            addCriterion("xSite between", value1, value2, "xsite");
            return (Criteria) this;
        }

        public Criteria andXsiteNotBetween(Double value1, Double value2) {
            addCriterion("xSite not between", value1, value2, "xsite");
            return (Criteria) this;
        }

        public Criteria andYsiteIsNull() {
            addCriterion("ySite is null");
            return (Criteria) this;
        }

        public Criteria andYsiteIsNotNull() {
            addCriterion("ySite is not null");
            return (Criteria) this;
        }

        public Criteria andYsiteEqualTo(Double value) {
            addCriterion("ySite =", value, "ysite");
            return (Criteria) this;
        }

        public Criteria andYsiteNotEqualTo(Double value) {
            addCriterion("ySite <>", value, "ysite");
            return (Criteria) this;
        }

        public Criteria andYsiteGreaterThan(Double value) {
            addCriterion("ySite >", value, "ysite");
            return (Criteria) this;
        }

        public Criteria andYsiteGreaterThanOrEqualTo(Double value) {
            addCriterion("ySite >=", value, "ysite");
            return (Criteria) this;
        }

        public Criteria andYsiteLessThan(Double value) {
            addCriterion("ySite <", value, "ysite");
            return (Criteria) this;
        }

        public Criteria andYsiteLessThanOrEqualTo(Double value) {
            addCriterion("ySite <=", value, "ysite");
            return (Criteria) this;
        }

        public Criteria andYsiteIn(List<Double> values) {
            addCriterion("ySite in", values, "ysite");
            return (Criteria) this;
        }

        public Criteria andYsiteNotIn(List<Double> values) {
            addCriterion("ySite not in", values, "ysite");
            return (Criteria) this;
        }

        public Criteria andYsiteBetween(Double value1, Double value2) {
            addCriterion("ySite between", value1, value2, "ysite");
            return (Criteria) this;
        }

        public Criteria andYsiteNotBetween(Double value1, Double value2) {
            addCriterion("ySite not between", value1, value2, "ysite");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table seller
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 15 10:40:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table seller
     *
     * @mbg.generated Thu Mar 15 10:40:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}